name: test_level_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  auto_route: ^3.2.4
  sqflite: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.9
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  image_picker: ^0.8.4+10
  logger: ^1.1.0
  flutter_hooks: ^0.18.2+1
  bloc_test: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator:
  build_runner:
  injectable_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/
